[build]
builder = "nixpacks"
buildCommand = "npm install && npm --workspace backend run build"

[deploy]
startCommand = "npm --workspace backend run start:prod"
healthcheckPath = "/api"
healthcheckTimeout = 60
restartPolicyType = "on_failure"

[variables]
NODE_ENV = "production"
FRONTEND_URL = "https://mawami.com"
NIXPACKS_NODE_VERSION = "20"