[build]
builder = "nixpacks"
buildCommand = "npm --workspace backend run build"

[deploy]
startCommand = "npm --workspace backend run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
NODE_ENV = "production"