[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build:backend"

[deploy]
startCommand = "npm run start:backend"
healthcheckPath = "/api"
healthcheckTimeout = 60
restartPolicyType = "on_failure"

[variables]
NODE_ENV = "production"
FRONTEND_URL = "https://mawami.com"