// Source notes (kept brief):
// • Official spellings follow government/BBS usage where applicable (e.g., Barishal, Chattogram, Cumilla, Jashore, Bogura, Jhalokati).
// • Includes UI-friendly options: "All Divisions", "All Districts", "All Upazilas" as requested.
// • City Corporations are NOT part of upazilas (kept strictly to 495 upazilas). If you want City Corporations added as selectable items, tell me which districts to include them under.
// • If you need Bangla spellings or geocodes, I can add them as fields later.

export type Upazila = string;
export type District = { name: string; upazilas?: Upazila[] };
export type Division = { name: string; districts?: District[] };
export type CountryGeo = { country: string; divisions: Division[] };

export const geoLocation: CountryGeo[] = [
  {
    country: "Bangladesh",
    divisions: [
      // ---- UI helper ----
      { name: "All Divisions" },

      // ======================= DHĀKĀ (DHAKA) DIVISION =======================
      {
        name: "Dhaka",
        districts: [
          { name: "All Districts" },
          {
            name: "Dhaka",
            upazilas: [
              "All Upazilas",
              "Dhamrai",
              "Dohar",
              "Keraniganj",
              "Nawabganj",
              "Savar",
            ],
          },
          {
            name: "Faridpur",
            upazilas: [
              "All Upazilas",
              "Alfadanga",
              "Bhanga",
              "Boalmari",
              "Char Bhadrasan",
              "Faridpur Sadar",
              "Madhukhali",
              "Nagarkanda",
              "Sadarpur",
              "Saltha",
            ],
          },
          {
            name: "Gazipur",
            upazilas: [
              "All Upazilas",
              "Gazipur Sadar",
              "Kaliakair",
              "Kaliganj",
              "Kapasia",
              "Sreepur",
            ],
          },
          {
            name: "Gopalganj",
            upazilas: [
              "All Upazilas",
              "Gopalganj Sadar",
              "Kashiani",
              "Kotalipara",
              "Muksudpur",
              "Tungipara",
            ],
          },
          {
            name: "Kishoreganj",
            upazilas: [
              "All Upazilas",
              "Austagram",
              "Bajitpur",
              "Bhairab",
              "Hossainpur",
              "Itna",
              "Karimganj",
              "Katiadi",
              "Kishoreganj Sadar",
              "Kuliarchar",
              "Mithamain",
              "Nikli",
              "Pakundia",
              "Tarail",
            ],
          },
          {
            name: "Madaripur",
            upazilas: [
              "All Upazilas",
              "Kalkini",
              "Madaripur Sadar",
              "Rajoir",
              "Shibchar",
            ],
          },
          {
            name: "Manikganj",
            upazilas: [
              "All Upazilas",
              "Daulatpur",
              "Ghior",
              "Harirampur",
              "Manikganj Sadar",
              "Saturia",
              "Shibalaya",
              "Singair",
            ],
          },
          {
            name: "Munshiganj",
            upazilas: [
              "All Upazilas",
              "Gazaria",
              "Lohajang",
              "Munshiganj Sadar",
              "Sirajdikhan",
              "Sreenagar",
              "Tongibari",
            ],
          },
          {
            name: "Narayanganj",
            upazilas: [
              "All Upazilas",
              "Araihazar",
              "Bandar",
              "Narayanganj Sadar",
              "Rupganj",
              "Sonargaon",
            ],
          },
          {
            name: "Narsingdi",
            upazilas: [
              "All Upazilas",
              "Belabo",
              "Monohardi",
              "Narsingdi Sadar",
              "Palash",
              "Raipura",
              "Shibpur",
            ],
          },
          {
            name: "Rajbari",
            upazilas: [
              "All Upazilas",
              "Baliakandi",
              "Goalanda",
              "Kalukhali",
              "Pangsha",
              "Rajbari Sadar",
            ],
          },
          {
            name: "Shariatpur",
            upazilas: [
              "All Upazilas",
              "Bhedarganj",
              "Damudya",
              "Gosairhat",
              "Naria",
              "Shariatpur Sadar",
              "Zanjira",
            ],
          },
          {
            name: "Tangail",
            upazilas: [
              "All Upazilas",
              "Basail",
              "Bhuapur",
              "Delduar",
              "Dhanbari",
              "Ghatail",
              "Gopalpur",
              "Kalihati",
              "Madhupur",
              "Mirzapur",
              "Nagarpur",
              "Sakhipur",
              "Tangail Sadar",
            ],
          },
        ],
      },

      // ======================= MYMENSINGH DIVISION =======================
      {
        name: "Mymensingh",
        districts: [
          { name: "All Districts" },
          {
            name: "Mymensingh",
            upazilas: [
              "All Upazilas",
              "Bhaluka",
              "Dhobaura",
              "Fulbaria",
              "Gaffargaon",
              "Gauripur",
              "Haluaghat",
              "Ishwarganj",
              "Mymensingh Sadar",
              "Muktagachha",
              "Nandail",
              "Phulpur",
              "Tarakanda",
              "Trishal",
            ],
          },
          {
            name: "Jamalpur",
            upazilas: [
              "All Upazilas",
              "Bakshiganj",
              "Dewanganj",
              "Islampur",
              "Jamalpur Sadar",
              "Madarganj",
              "Melandaha",
              "Sarishabari",
            ],
          },
          {
            name: "Netrokona",
            upazilas: [
              "All Upazilas",
              "Atpara",
              "Barhatta",
              "Durgapur",
              "Kalmakanda",
              "Kendua",
              "Khaliajuri",
              "Madan",
              "Mohanganj",
              "Netrokona Sadar",
              "Purbadhala",
            ],
          },
          {
            name: "Sherpur",
            upazilas: [
              "All Upazilas",
              "Jhenaigati",
              "Nakla",
              "Nalitabari",
              "Sherpur Sadar",
              "Sreebardi",
            ],
          },
        ],
      },

      // ======================= CHATTOGRAM DIVISION =======================
      {
        name: "Chattogram",
        districts: [
          { name: "All Districts" },
          {
            name: "Chattogram",
            upazilas: [
              "All Upazilas",
              "Anwara",
              "Banshkhali",
              "Boalkhali",
              "Chandanaish",
              "Fatikchhari",
              "Hathazari",
              "Karnaphuli",
              "Lohagara",
              "Mirsharai",
              "Patiya",
              "Rangunia",
              "Raozan",
              "Sandwip",
              "Satkania",
              "Sitakunda",
            ],
          },
          {
            name: "Cox's Bazar",
            upazilas: [
              "All Upazilas",
              "Chakaria",
              "Cox's Bazar Sadar",
              "Kutubdia",
              "Maheshkhali",
              "Pekua",
              "Ramu",
              "Teknaf",
              "Ukhia",
            ],
          },
          {
            name: "Cumilla",
            upazilas: [
              "All Upazilas",
              "Barura",
              "Brahmanpara",
              "Burichang",
              "Chandina",
              "Chauddagram",
              "Cumilla Adarsha Sadar",
              "Cumilla Sadar Dakshin",
              "Daudkandi",
              "Debidwar",
              "Homna",
              "Laksam",
              "Lalmai",
              "Meghna",
              "Monoharganj",
              "Muradnagar",
              "Nangalkot",
              "Titas",
            ],
          },
          {
            name: "Feni",
            upazilas: [
              "All Upazilas",
              "Chhagalnaiya",
              "Daganbhuiyan",
              "Feni Sadar",
              "Fulgazi",
              "Parshuram",
              "Sonagazi",
            ],
          },
          {
            name: "Brahmanbaria",
            upazilas: [
              "All Upazilas",
              "Akhaura",
              "Ashuganj",
              "Bancharampur",
              "Bijoynagar",
              "Brahmanbaria Sadar",
              "Kasba",
              "Nabinagar",
              "Nasirnagar",
              "Sarail",
            ],
          },
          {
            name: "Chandpur",
            upazilas: [
              "All Upazilas",
              "Chandpur Sadar",
              "Faridganj",
              "Haimchar",
              "Hajiganj",
              "Kachua",
              "Matlab Dakshin",
              "Matlab Uttar",
              "Shahrasti",
            ],
          },
          {
            name: "Noakhali",
            upazilas: [
              "All Upazilas",
              "Begumganj",
              "Chatkhil",
              "Companiganj",
              "Hatiya",
              "Kabirhat",
              "Noakhali Sadar",
              "Senbagh",
              "Sonaimuri",
              "Subarnachar",
            ],
          },
          {
            name: "Lakshmipur",
            upazilas: [
              "All Upazilas",
              "Kamalnagar",
              "Lakshmipur Sadar",
              "Raipur",
              "Ramganj",
              "Ramgati",
            ],
          },
          {
            name: "Khagrachhari",
            upazilas: [
              "All Upazilas",
              "Dighinala",
              "Khagrachhari Sadar",
              "Lakshmichhari",
              "Mahalchhari",
              "Manikchhari",
              "Matiranga",
              "Panchhari",
              "Ramgarh",
            ],
          },
          {
            name: "Rangamati",
            upazilas: [
              "All Upazilas",
              "Baghaichhari",
              "Barkal",
              "Juraichhari",
              "Kaptai",
              "Kawkhali",
              "Langadu",
              "Naniarchar",
              "Rajasthali",
              "Rangamati Sadar",
            ],
          },
          {
            name: "Bandarban",
            upazilas: [
              "All Upazilas",
              "Ali Kadam",
              "Bandarban Sadar",
              "Lama",
              "Naikhongchhari",
              "Rowangchhari",
              "Ruma",
              "Thanchi",
            ],
          },
        ],
      },

      // ======================= SYLHET DIVISION =======================
      {
        name: "Sylhet",
        districts: [
          { name: "All Districts" },
          {
            name: "Sylhet",
            upazilas: [
              "All Upazilas",
              "Balaganj",
              "Beanibazar",
              "Bishwanath",
              "Companiganj",
              "Dakshin Surma",
              "Fenchuganj",
              "Golapganj",
              "Gowainghat",
              "Jaintiapur",
              "Kanaighat",
              "Osmani Nagar",
              "Sylhet Sadar",
              "Zakiganj",
            ],
          },
          {
            name: "Moulvibazar",
            upazilas: [
              "All Upazilas",
              "Barlekha",
              "Juri",
              "Kamalganj",
              "Kulaura",
              "Moulvibazar Sadar",
              "Rajnagar",
              "Sreemangal",
            ],
          },
          {
            name: "Habiganj",
            upazilas: [
              "All Upazilas",
              "Ajmiriganj",
              "Bahubal",
              "Baniachong",
              "Chunarughat",
              "Habiganj Sadar",
              "Lakhai",
              "Madhabpur",
              "Nabiganj",
              "Shayestaganj",
            ],
          },
          {
            name: "Sunamganj",
            upazilas: [
              "All Upazilas",
              "Bishwamvarpur",
              "Chhatak",
              "Derai",
              "Dharampasha",
              "Dowarabazar",
              "Jagannathpur",
              "Jamalganj",
              "Sullah",
              "Sunamganj Sadar",
              "Tahirpur",
              "South Sunamganj",
            ],
          },
        ],
      },

      // ======================= RAJSHAHI DIVISION =======================
      {
        name: "Rajshahi",
        districts: [
          { name: "All Districts" },
          {
            name: "Rajshahi",
            upazilas: [
              "All Upazilas",
              "Bagha",
              "Bagmara",
              "Charghat",
              "Durgapur",
              "Godagari",
              "Mohanpur",
              "Paba",
              "Puthia",
              "Tanore",
            ],
          },
          {
            name: "Naogaon",
            upazilas: [
              "All Upazilas",
              "Atrai",
              "Badalgachhi",
              "Dhamoirhat",
              "Manda",
              "Mohadevpur",
              "Naogaon Sadar",
              "Niamatpur",
              "Patnitala",
              "Porsha",
              "Raninagar",
              "Sapahar",
            ],
          },
          {
            name: "Natore",
            upazilas: [
              "All Upazilas",
              "Bagatipara",
              "Baraigram",
              "Gurudaspur",
              "Lalpur",
              "Natore Sadar",
              "Singra",
            ],
          },
          {
            name: "Chapainawabganj",
            upazilas: [
              "All Upazilas",
              "Bholahat",
              "Chapainawabganj Sadar",
              "Gomastapur",
              "Nachole",
              "Shibganj",
            ],
          },
          {
            name: "Pabna",
            upazilas: [
              "All Upazilas",
              "Atgharia",
              "Bera",
              "Bhangura",
              "Chatmohar",
              "Faridpur",
              "Ishwardi",
              "Pabna Sadar",
              "Santhia",
              "Sujanagar",
            ],
          },
          {
            name: "Sirajganj",
            upazilas: [
              "All Upazilas",
              "Belkuchi",
              "Chauhali",
              "Kamarkhanda",
              "Kazipur",
              "Raiganj",
              "Shahjadpur",
              "Sirajganj Sadar",
              "Tarash",
              "Ullapara",
            ],
          },
          {
            name: "Bogura",
            upazilas: [
              "All Upazilas",
              "Adamdighi",
              "Bogura Sadar",
              "Dhunat",
              "Dhupchanchia",
              "Gabtali",
              "Kahaloo",
              "Nandigram",
              "Sariakandi",
              "Shajahanpur",
              "Sherpur",
              "Shibganj",
              "Sonatala",
            ],
          },
          {
            name: "Joypurhat",
            upazilas: [
              "All Upazilas",
              "Akkelpur",
              "Joypurhat Sadar",
              "Kalai",
              "Khetlal",
              "Panchbibi",
            ],
          },
        ],
      },

      // ======================= RANGPUR DIVISION =======================
      {
        name: "Rangpur",
        districts: [
          { name: "All Districts" },
          {
            name: "Rangpur",
            upazilas: [
              "All Upazilas",
              "Badarganj",
              "Gangachara",
              "Kaunia",
              "Mithapukur",
              "Pirgachha",
              "Pirganj",
              "Rangpur Sadar",
              "Taraganj",
            ],
          },
          {
            name: "Dinajpur",
            upazilas: [
              "All Upazilas",
              "Birampur",
              "Birganj",
              "Biral",
              "Bochaganj",
              "Chirirbandar",
              "Dinajpur Sadar",
              "Fulbari",
              "Ghoraghat",
              "Hakimpur",
              "Kaharole",
              "Khansama",
              "Nawabganj",
              "Parbatipur",
            ],
          },
          {
            name: "Kurigram",
            upazilas: [
              "All Upazilas",
              "Bhurungamari",
              "Char Rajibpur",
              "Chilmari",
              "Phulbari",
              "Kurigram Sadar",
              "Nageshwari",
              "Rajarhat",
              "Rowmari",
              "Ulipur",
            ],
          },
          {
            name: "Gaibandha",
            upazilas: [
              "All Upazilas",
              "Fulchhari",
              "Gaibandha Sadar",
              "Gobindaganj",
              "Palashbari",
              "Sadullapur",
              "Saghata",
              "Sundarganj",
            ],
          },
          {
            name: "Nilphamari",
            upazilas: [
              "All Upazilas",
              "Dimla",
              "Domar",
              "Jaldhaka",
              "Kishoreganj",
              "Nilphamari Sadar",
              "Saidpur",
            ],
          },
          {
            name: "Lalmonirhat",
            upazilas: [
              "All Upazilas",
              "Aditmari",
              "Hatibandha",
              "Kaliganj",
              "Lalmonirhat Sadar",
              "Patgram",
            ],
          },
          {
            name: "Panchagarh",
            upazilas: [
              "All Upazilas",
              "Atwari",
              "Boda",
              "Debiganj",
              "Panchagarh Sadar",
              "Tetulia",
            ],
          },
          {
            name: "Thakurgaon",
            upazilas: [
              "All Upazilas",
              "Baliadangi",
              "Haripur",
              "Pirganj",
              "Ranisankail",
              "Thakurgaon Sadar",
            ],
          },
        ],
      },

      // ======================= KHULNA DIVISION =======================
      {
        name: "Khulna",
        districts: [
          { name: "All Districts" },
          {
            name: "Khulna",
            upazilas: [
              "All Upazilas",
              "Batiaghata",
              "Dacope",
              "Dighalia",
              "Dumuria",
              "Koyra",
              "Paikgachha",
              "Phultala",
              "Rupsha",
              "Terokhada",
            ],
          },
          {
            name: "Bagerhat",
            upazilas: [
              "All Upazilas",
              "Bagerhat Sadar",
              "Chitalmari",
              "Fakirhat",
              "Kachua",
              "Mollahat",
              "Mongla",
              "Morrelganj",
              "Rampal",
              "Sarankhola",
            ],
          },
          {
            name: "Satkhira",
            upazilas: [
              "All Upazilas",
              "Assasuni",
              "Debhata",
              "Kalaroa",
              "Kaliganj",
              "Satkhira Sadar",
              "Shyamnagar",
              "Tala",
            ],
          },
          {
            name: "Jashore",
            upazilas: [
              "All Upazilas",
              "Abhaynagar",
              "Bagherpara",
              "Chaugachha",
              "Jhikargachha",
              "Keshabpur",
              "Jashore Sadar",
              "Manirampur",
              "Sharsha",
            ],
          },
          {
            name: "Jhenaidah",
            upazilas: [
              "All Upazilas",
              "Harinakunda",
              "Jhenaidah Sadar",
              "Kaliganj",
              "Kotchandpur",
              "Maheshpur",
              "Shailkupa",
            ],
          },
          {
            name: "Magura",
            upazilas: [
              "All Upazilas",
              "Magura Sadar",
              "Mohammadpur",
              "Shalikha",
              "Sreepur",
            ],
          },
          {
            name: "Narail",
            upazilas: [
              "All Upazilas",
              "Kalia",
              "Lohagara",
              "Narail Sadar",
            ],
          },
          {
            name: "Chuadanga",
            upazilas: [
              "All Upazilas",
              "Alamdanga",
              "Chuadanga Sadar",
              "Damurhuda",
              "Jibannagar",
            ],
          },
          {
            name: "Kushtia",
            upazilas: [
              "All Upazilas",
              "Bheramara",
              "Daulatpur",
              "Khoksa",
              "Kumarkhali",
              "Kushtia Sadar",
              "Mirpur",
            ],
          },
          {
            name: "Meherpur",
            upazilas: [
              "All Upazilas",
              "Gangni",
              "Meherpur Sadar",
              "Mujibnagar",
            ],
          },
        ],
      },

      // ======================= BARISHAL DIVISION =======================
      {
        name: "Barishal",
        districts: [
          { name: "All Districts" },
          {
            name: "Barishal",
            upazilas: [
              "All Upazilas",
              "Agailjhara",
              "Babuganj",
              "Bakerganj",
              "Banaripara",
              "Barishal Sadar",
              "Gournadi",
              "Hizla",
              "Mehendiganj",
              "Muladi",
              "Wazirpur",
            ],
          },
          {
            name: "Patuakhali",
            upazilas: [
              "All Upazilas",
              "Bauphal",
              "Dashmina",
              "Dumki",
              "Galachipa",
              "Kalapara",
              "Mirzaganj",
              "Patuakhali Sadar",
              "Rangabali",
            ],
          },
          {
            name: "Bhola",
            upazilas: [
              "All Upazilas",
              "Bhola Sadar",
              "Burhanuddin",
              "Char Fasson",
              "Daulatkhan",
              "Lalmohan",
              "Manpura",
              "Tazumuddin",
            ],
          },
          {
            name: "Barguna",
            upazilas: [
              "All Upazilas",
              "Amtali",
              "Bamna",
              "Barguna Sadar",
              "Betagi",
              "Patharghata",
              "Taltali",
            ],
          },
          {
            name: "Jhalokati",
            upazilas: [
              "All Upazilas",
              "Jhalokati Sadar",
              "Kathalia",
              "Nalchity",
              "Rajapur",
            ],
          },
          {
            name: "Pirojpur",
            upazilas: [
              "All Upazilas",
              "Bhandaria",
              "Kawkhali",
              "Mathbaria",
              "Nazirpur",
              "Nesarabad",
              "Pirojpur Sadar",
              "Indurkani",
            ],
          },
        ],
      },
    ],
  },
];
