export async function seedBiodata(dataSource: any): Promise<void> {
  const userRow = await dataSource.query(`SELECT id, "fullName", email FROM "user" WHERE email = $1 LIMIT 1`, ['user@finder.com']);
  if (!userRow.length) {
    console.log('⚠️ user@finder.com not found; skipping demo biodata creation.');
    return;
  }

  const userId = userRow[0].id;
  const existingBiodata = await dataSource.query(`SELECT id FROM biodata WHERE "userId" = $1 LIMIT 1`, [userId]);
  if (existingBiodata.length > 0) {
    console.log('ℹ️ Demo biodata already exists for user@finder.com. Skipping.');
    return;
  }

  console.log('🌱 Creating demo biodata for user@finder.com...');
  await dataSource.query(`
    INSERT INTO "biodata" (
      "step",
      "userId",
      "completedSteps",
      "partnerAgeMin",
      "partnerAgeMax",
      "sameAsPermanent",
      "religion",
      "biodataType",
      "maritalStatus",
      "dateOfBirth",
      "age",
      "height",
      "weight",
      "complexion",
      "profession",
      "bloodGroup",
      "permanentCountry",
      "permanentDivision",
      "permanentZilla",
      "permanentUpazilla",
      "permanentArea",
      "presentCountry",
      "presentDivision",
      "presentZilla",
      "presentUpazilla",
      "presentArea",
      "healthIssues",
      "educationMedium",
      "highestEducation",
      "instituteName",
      "subject",
      "passingYear",
      "result",
      "economicCondition",
      "fatherName",
      "fatherProfession",
      "fatherAlive",
      "motherName",
      "motherProfession",
      "motherAlive",
      "brothersCount",
      "sistersCount",
      "familyDetails",
      "partnerComplexion",
      "partnerHeight",
      "partnerEducation",
      "partnerProfession",
      "partnerLocation",
      "partnerDetails",
      "fullName",
      "profilePicture",
      "email",
      "guardianMobile",
      "ownMobile",
      "biodataApprovalStatus",
      "biodataVisibilityStatus",
      "viewCount"
    ) VALUES (
      $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19,
      $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36,
      $37, $38, $39, $40, $41, $42, $43, $44, $45, $46, $47, $48, $49, $50, $51, $52, $53, $54, $55, $56, $57
    )
  `, [
    5,
    userId,
    '1,2,3,4,5',
    22,
    28,
    false,
    'Islam',
    'Male',
    'Unmarried',
    '1997-01-15',
    28,
    '5.7',
    70,
    'Fair',
    'Software Engineer',
    'O+',
    'Bangladesh',
    'Dhaka',
    'Dhaka',
    'Tejgaon',
    'Road 12, House 34',
    'Bangladesh',
    'Dhaka',
    'Dhaka',
    'Tejgaon',
    'Road 12, House 34',
    'None',
    'English',
    'Honours',
    'BUET',
    'Computer Science and Engineering',
    '2019',
    'A+',
    'Middle Class',
    'Md. Abdul Rahman',
    'Business',
    'Yes',
    'Fatema Begum',
    'Housewife',
    'Yes',
    1,
    2,
    'We are a middle-class family with strong values and education focus.',
    'Fair',
    '5ft 2in to 5ft 6in',
    'Honours or above',
    'Teacher or Government Job',
    'Dhaka or nearby areas',
    'Looking for a kind, educated and religious partner from a good family',
    userRow[0].fullName || 'Test User',
    null,
    'user@finder.com',
    '01700000000',
    '01800000000',
    'pending',
    'active',
    0
  ]);
}


